version: '3.7'
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
  - AIRFLOW__CORE__LOAD_EXAMPLES=False
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://postgres:password@postgres:5432/postgres
  - AIRFLOW__CORE__STORE_DAG_CODE=True
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
  - AIRFLOW__WEBSERVER__RBAC=False
x-airflow-image: &airflow_image extending_airflow:latest
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@moneylion.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - '80:80'
  init:
    image: *airflow_image
    container_name: airflow_init
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow db init && airflow users create --username khee --password password --firstname ling --lastname khee --role Admin --email admin@gmail.com'
  webserver:
    image: *airflow_image
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./Airflow Setup/logs:/opt/airflow/logs
    environment: *airflow_environment
    command: webserver
  scheduler:
    image: *airflow_image
    container_name: airflow_scheduler
    restart: always
    user: root
    depends_on:
      - postgres
      - webserver
    volumes:
      - ./Airflow Setup/dags:/opt/airflow/dags
      - ./Airflow Setup/configurations.json:/tmp/conf_file/configurations.json
      - ./Airflow Setup/logs:/opt/airflow/logs
      - ./Airflow Setup/dags/data:/opt/airflow/dags/data
    environment: *airflow_environment
    command: scheduler
volumes:
  logs: